[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/listings"
  status = 200

  [[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
